### ISSUE TITLE
TikTok "Unknow error "FailedParseRoomIdError", see logs for more information

### ISSUE THREAD

**Issue by ther3y3s** [3dproger/AxelChat#456]
Hi, i always get this error when i try to add tiktok. I want to know how i can fix it?
![image](https://github.com/3dproger/AxelChat/assets/35653733/8389dfe7-465a-41a5-a6bb-a9c841c3f0e9)
But if i press on stream button i see my channel so...

I try to add in tiktok channel my username, my @username and my page link but i get always the same error

**Comment by 3dproger** [comment]
Hello, usually this error is fixed if you open the tiktok page in a browser on the same device where AxelChat is running. Let me know if this didn't help. In any case, I will try to fix this problem in the future

**Comment by ther3y3s** [comment]
I alredy tried to open tiktok page by pressing the stream button. And i opened the tiktok page on chrome too and i'm alredy logged in with my account but nothing, still the same problem

**Comment by 3dproger** [comment]
Okay, was VPN enabled in the browser when opening TikTok in the browser?

**Comment by ther3y3s** [comment]
nope

**Comment by 3dproger** [comment]
Okay, thanks for the report, I'll look into it

**Comment by 3dproger** [comment]
I managed to fix this problem. In the latest update you can download: https://github.com/3dproger/AxelChat/releases/tag/0.36.3-beta

**Comment by ther3y3s** [comment]
Thanks <3
